version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    build: ./
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=yii-basic
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1165
      - MYSQL_ROOT_PASSWORD=1165

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1165
      UPLOAD_LIMIT: 3000000000
    ports:
      - "8000:80"