version: '2'
services:
  php:
    build: .
    environment:
      - GITHUB_API_TOKEN
    volumes:
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./vendor:/app/vendor
      - ./config:/app/config
      - ./src:/app/src
      - ./web:/app/web
      - ./tests:/app/tests
      - ./codeception.yml:/app/codeception.yml
      # composer-cache on host-volume
      - ~/.composer-docker/cache:/root/.composer/cache
    ports:
      - 20080:80
